// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYNSnSyTyVfMYAB7yw7nRJqidsQKp30E',
    appId: '1:1026198934075:android:e78fefc5236a3c4dc0c21e',
    messagingSenderId: '1026198934075',
    projectId: 'the-eap-app',
    storageBucket: 'the-eap-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9jBPxeOwKkZ7TbAmogPfG5AzvFZaI40',
    appId: '1:1026198934075:ios:1fa398128fd0ba56c0c21e',
    messagingSenderId: '1026198934075',
    projectId: 'the-eap-app',
    storageBucket: 'the-eap-app.firebasestorage.app',
    iosBundleId: 'com.theeap.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAK83Ya303I7iFe1jZw390w4WYURLu_r4',
    appId: '1:1026198934075:web:c4dee442bed4643ec0c21e',
    messagingSenderId: '1026198934075',
    projectId: 'the-eap-app',
    authDomain: 'the-eap-app.firebaseapp.com',
    storageBucket: 'the-eap-app.firebasestorage.app',
    measurementId: 'G-6L0QTVZ2NT',
  );

}